// <auto-generated />
using System;
using GeocodingAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GeocodingAPI.Migrations
{
    [DbContext(typeof(GeocodingAPIDbContext))]
    partial class GeocodingAPIDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.28");

            modelBuilder.Entity("GeocodingAPI.Models.CanadianAddress", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("BuildingNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Direction")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("HashValue")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<string>("PostalCode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ProvinceName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ProvinceNumber")
                        .HasColumnType("INTEGER");

                    b.Property<string>("StreetName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.ToTable("CanadianAddresseses");
                });

            modelBuilder.Entity("GeocodingAPI.Models.GeoCodeRequest", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long?>("CanadianAddressID")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("GeoCodeResponseID")
                        .HasColumnType("INTEGER");

                    b.Property<long>("UserRequestID")
                        .HasColumnType("INTEGER");

                    b.HasKey("ID");

                    b.HasIndex("CanadianAddressID");

                    b.HasIndex("GeoCodeResponseID");

                    b.ToTable("GeoCodeRequests");
                });

            modelBuilder.Entity("GeocodingAPI.Models.GeoCodeResponse", b =>
                {
                    b.Property<long>("PlaceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasAnnotation("Relational:JsonPropertyName", "place_id");

                    b.Property<string>("AddressType")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "addresstype");

                    b.Property<string>("BoundingBox")
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "boundingbox");

                    b.Property<string>("ClassName")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "class");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "display_name");

                    b.Property<decimal>("Importance")
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "importance");

                    b.Property<string>("Latitude")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "lat");

                    b.Property<string>("Licence")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "licence");

                    b.Property<string>("Longitude")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "lon");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "name");

                    b.Property<long>("OSMId")
                        .HasColumnType("INTEGER")
                        .HasAnnotation("Relational:JsonPropertyName", "osm_id");

                    b.Property<string>("OSMType")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "osm_type");

                    b.Property<int>("PlaceRank")
                        .HasColumnType("INTEGER")
                        .HasAnnotation("Relational:JsonPropertyName", "place_rank");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "type");

                    b.HasKey("PlaceId");

                    b.ToTable("GeoCodeResponses");
                });

            modelBuilder.Entity("GeocodingAPI.Models.UserRequest", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<byte[]>("HashValue")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<string>("OriginalAddress")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.ToTable("UserRequests");
                });

            modelBuilder.Entity("GeocodingAPI.Models.UserRequestEachAddress", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("EachAddress")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ErrorInAddress")
                        .HasColumnType("TEXT");

                    b.Property<long?>("GeoCodeRequestID")
                        .HasColumnType("INTEGER");

                    b.Property<byte[]>("HashValue")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.HasKey("ID");

                    b.HasIndex("GeoCodeRequestID");

                    b.HasIndex("HashValue");

                    b.ToTable("UserRequestEachAddresses");
                });

            modelBuilder.Entity("GeocodingAPI.Models.GeoCodeRequest", b =>
                {
                    b.HasOne("GeocodingAPI.Models.CanadianAddress", "CanadianAddress")
                        .WithMany()
                        .HasForeignKey("CanadianAddressID");

                    b.HasOne("GeocodingAPI.Models.GeoCodeResponse", "GeoCodeResponse")
                        .WithMany()
                        .HasForeignKey("GeoCodeResponseID");

                    b.Navigation("CanadianAddress");

                    b.Navigation("GeoCodeResponse");
                });

            modelBuilder.Entity("GeocodingAPI.Models.GeoCodeResponse", b =>
                {
                    b.OwnsOne("GeocodingAPI.Models.GeoCodeResponseAddress", "address", b1 =>
                        {
                            b1.Property<long>("GeoCodeResponsePlaceId")
                                .HasColumnType("INTEGER");

                            b1.Property<string>("City")
                                .IsRequired()
                                .HasColumnType("TEXT")
                                .HasAnnotation("Relational:JsonPropertyName", "city");

                            b1.Property<string>("CityDistrict")
                                .IsRequired()
                                .HasColumnType("TEXT")
                                .HasAnnotation("Relational:JsonPropertyName", "city_district");

                            b1.Property<string>("Country")
                                .IsRequired()
                                .HasColumnType("TEXT")
                                .HasAnnotation("Relational:JsonPropertyName", "country");

                            b1.Property<string>("CountryCode")
                                .IsRequired()
                                .HasColumnType("TEXT")
                                .HasAnnotation("Relational:JsonPropertyName", "country_code");

                            b1.Property<string>("County")
                                .IsRequired()
                                .HasColumnType("TEXT")
                                .HasAnnotation("Relational:JsonPropertyName", "county");

                            b1.Property<string>("ISO3166")
                                .IsRequired()
                                .HasColumnType("TEXT")
                                .HasAnnotation("Relational:JsonPropertyName", "ISO3166-2-lvl4");

                            b1.Property<string>("Neighbourhood")
                                .IsRequired()
                                .HasColumnType("TEXT")
                                .HasAnnotation("Relational:JsonPropertyName", "neighbourhood");

                            b1.Property<string>("Postcode")
                                .IsRequired()
                                .HasColumnType("TEXT")
                                .HasAnnotation("Relational:JsonPropertyName", "postcode");

                            b1.Property<string>("Road")
                                .IsRequired()
                                .HasColumnType("TEXT")
                                .HasAnnotation("Relational:JsonPropertyName", "road");

                            b1.Property<string>("State")
                                .IsRequired()
                                .HasColumnType("TEXT")
                                .HasAnnotation("Relational:JsonPropertyName", "state");

                            b1.HasKey("GeoCodeResponsePlaceId");

                            b1.ToTable("GeoCodeResponses");

                            b1.HasAnnotation("Relational:JsonPropertyName", "address");

                            b1.WithOwner()
                                .HasForeignKey("GeoCodeResponsePlaceId");
                        });

                    b.Navigation("address");
                });

            modelBuilder.Entity("GeocodingAPI.Models.UserRequestEachAddress", b =>
                {
                    b.HasOne("GeocodingAPI.Models.GeoCodeRequest", "GeoCodeRequests")
                        .WithMany()
                        .HasForeignKey("GeoCodeRequestID");

                    b.Navigation("GeoCodeRequests");
                });
#pragma warning restore 612, 618
        }
    }
}
